// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_ValidateLogin from "./routes/api/ValidateLogin.ts";
import * as $api_cookieLog from "./routes/api/cookieLog.ts";
import * as $index from "./routes/index.tsx";
import * as $ActiveUser from "./islands/ActiveUser.tsx";
import * as $AddCookie from "./islands/AddCookie.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $HomePage from "./islands/HomePage.tsx";
import * as $LogOptions from "./islands/LogOptions.tsx";
import * as $LoginPopup from "./islands/LoginPopup.tsx";
import * as $SearchFilters from "./islands/SearchFilters.tsx";
import * as $SignupPopup from "./islands/SignupPopup.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/ValidateLogin.ts": $api_ValidateLogin,
    "./routes/api/cookieLog.ts": $api_cookieLog,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ActiveUser.tsx": $ActiveUser,
    "./islands/AddCookie.tsx": $AddCookie,
    "./islands/Counter.tsx": $Counter,
    "./islands/Header.tsx": $Header,
    "./islands/HomePage.tsx": $HomePage,
    "./islands/LogOptions.tsx": $LogOptions,
    "./islands/LoginPopup.tsx": $LoginPopup,
    "./islands/SearchFilters.tsx": $SearchFilters,
    "./islands/SignupPopup.tsx": $SignupPopup,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
