// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $add_index from "./routes/add/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $search_id_ from "./routes/search/[id].tsx";
import * as $search_a from "./routes/search/a.tsx";
import * as $search_index from "./routes/search/index.tsx";
import * as $CharactersSearch from "./islands/CharactersSearch.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/add/index.tsx": $add_index,
    "./routes/index.tsx": $index,
    "./routes/search/[id].tsx": $search_id_,
    "./routes/search/a.tsx": $search_a,
    "./routes/search/index.tsx": $search_index,
  },
  islands: {
    "./islands/CharactersSearch.tsx": $CharactersSearch,
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
