// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $add from "./routes/add.tsx";
import * as $all from "./routes/all.tsx";
import * as $api_addCharacter from "./routes/api/addCharacter.ts";
import * as $api_deleteCharacter from "./routes/api/deleteCharacter.ts";
import * as $borrar from "./routes/borrar.tsx";
import * as $index from "./routes/index.tsx";
import * as $search from "./routes/search.tsx";
import * as $Character from "./islands/Character.tsx";
import * as $CharacterAddForm from "./islands/CharacterAddForm.tsx";
import * as $CharactersSearch from "./islands/CharactersSearch.tsx";
import * as $DeleteButton from "./islands/DeleteButton.tsx";
import * as $borrar_1 from "./islands/borrar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/add.tsx": $add,
    "./routes/all.tsx": $all,
    "./routes/api/addCharacter.ts": $api_addCharacter,
    "./routes/api/deleteCharacter.ts": $api_deleteCharacter,
    "./routes/borrar.tsx": $borrar,
    "./routes/index.tsx": $index,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/Character.tsx": $Character,
    "./islands/CharacterAddForm.tsx": $CharacterAddForm,
    "./islands/CharactersSearch.tsx": $CharactersSearch,
    "./islands/DeleteButton.tsx": $DeleteButton,
    "./islands/borrar.tsx": $borrar_1,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
